# KerogsPHP Framework Configuration
# https://github.com/KSInfinite/KerogsPHP-Framework
# Thanks for using it.

# SEO Configuration
seo:
  title: "PyHwa2"
  title_short: "PyHwa2"
  description: "Small python application for reading manhwa/manhua/manga."
  keywords: "Manhwa, Manhua, Manga, Reader, Scan, PyHwa, PyHwa2"
  author: "Kerogs"
  lang: "English"
  lang_short: "en"
  color: "#a038ec"
  image: "h"
  favicon: "src/img/favicon.ico"
  sitemap: "src/xml/sitemap.xml"

# Labs/test IP authorization Configuration
labs:
  enable: false
  labsIPAuth:
    - 127.0.0.1

# Other
other:
  website_version: 1.0.0
  
  use_database: false
  db_in_env:
    # add database login in .env (recommended to true)
    auto_add_db_in_env: true

  # .env informations
  env:
    # if true all value in .env will be automatically added in $_ENV
    use_env: true
    auto_generate_env: true
    
    admin:
      add_login_admin: true
      # admin password automattically hashed (changed automatically in .env if you change it)
      admin_password: "pyhwa123"

framework:
  framework_version: 2.4.2-sh15
  title: "KerogsPHP Framework"
  title_short: "KsPHP Framework"